DEFAULT rk3326-charge-test
TIMEOUT 30
MENU TITLE RK3326 tablet OEM charger test

LABEL rk3326-charge-test
	LINUX /Image-6.1-rockchip
	FDT /rk3326-863-tablet-charge-test.dtb
	APPEND root=PARTUUID=@ROOT_PARTUUID@ rootfstype=ext4 rw rootwait console=ttyS2,1500000n8 console=tty0 loglevel=8 earlycon=uart8250,mmio32,0xff160000 video=DSI-1:1024x600@60
