DEFAULT rk3326-uart
TIMEOUT 30
MENU TITLE RK3326 tablet bring-up

LABEL rk3326-uart
	LINUX /Image-6.1-rockchip
	FDT /rk3326-863-tablet-uart.dtb
	APPEND root=PARTUUID=@ROOT_PARTUUID@ rootfstype=ext4 rw rootwait console=ttyS2,1500000n8 console=tty0 loglevel=8 earlycon=uart8250,mmio32,0xff160000
